"""making initial changes to db

Revision ID: d25a8a8cfbc3
Revises: 
Create Date: 2025-01-27 01:22:02.108497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd25a8a8cfbc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('lname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('work_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.String(length=255), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_email_verified'), 'users', ['email_verified'], unique=False)
    op.create_index(op.f('ix_users_fname'), 'users', ['fname'], unique=False)
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_lname'), 'users', ['lname'], unique=False)
    op.create_index(op.f('ix_users_work_email'), 'users', ['work_email'], unique=False)
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_users_work_email'), table_name='users')
    op.drop_index(op.f('ix_users_lname'), table_name='users')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_index(op.f('ix_users_fname'), table_name='users')
    op.drop_index(op.f('ix_users_email_verified'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'work_email')
    op.drop_column('users', 'lname')
    op.drop_column('users', 'fname')
    # ### end Alembic commands ###
